### ISSUE TITLE
✨ 推荐一个【李志】酷炫音乐播放器

### ISSUE THREAD

**Issue by turkyden** [Lcry/a-sheep-assistant#107]
访问地址：https://github.com/turkyden/lizhi-app

- [x] 资源 Github 托管, 永久有效
- [x] CDN 全球免费加速
- [x] 在线播放
- [x] 直接下载

![image](https://user-images.githubusercontent.com/24560160/187070336-1137a71a-89b4-4fac-91e2-10cbfaba4fb5.png)

**Comment by Camefor** [comment]
逼粉路过，感谢推荐！~
