### ISSUE TITLE
参照楼上老哥给的新接口，修改了羊群通关代码，各位自取

### ISSUE THREAD

**Issue by zhamenghui** [Lcry/a-sheep-assistant#110]
# 修改新的羊群通关接口
finish_sheep_api = "https://cat-match.easygame2021.com/sheep/v1/game/game_over_ex"

# 修改发送通关消息函数
`def finish_game_sheep(skin, rank_time):
    s = requests.session()
    s.keep_alive = False
    finish_body = {"rank_score": 1, "rank_state": 1, "rank_time": rank_time, "rank_role": 1, "skin": 1, 
    "MatchPlayInfo": "CAMiBQjnARAAIgYI5gEQ2wEiBgiAAhDWASIGCP8BEN8BIgYInwIQsAQiBgieAhCQAyIGCJwCENEH"}
    res = requests.post(finish_sheep_api, data=finish_body, headers=request_header, timeout=10, verify=True)
    # err_code为0则成功
    if res.json()["err_code"] == 0:
        print("[恭喜你! 本次闯关羊群状态成功]")
    else:
        print(res.json())
        print("请检查t的值是否获取正确!")`

**Comment by k9ox38** [comment]
可以可以👍

**Comment by liuxiaofeng8888** [comment]
还是没用吧。你们的通关次数生效吗

**Comment by zhamenghui** [comment]
> 

记得header里添加t，
![image](https://user-images.githubusercontent.com/38780241/190988562-50294621-4d20-4e29-afd0-a66663e48420.png)

**Comment by zhangchenyang1991** [comment]
可以

**Comment by Yangchun789** [comment]
是不是又失效啦。 次数更新不了啦

**Comment by Iitianci** [comment]
失效了

**Comment by jianan134** [comment]
失效了

**Comment by xianyunyehexjy** [comment]
失效了

**Comment by Lcry** [comment]
失效了

**Comment by Warm-rain** [comment]
不是失效了，是别人服务器加了限制，四个半小时只能通关一次。

**Comment by yanpengqing** [comment]
试了很多次 
每日话题通过次数增加了 加入羊群次数一直都是0

**Comment by ocean-zhc** [comment]
> 试了很多次 每日话题通过次数增加了 排行榜通关次数一直都是0

+1
