### ISSUE TITLE
获取 user token 时 参数 错误

### ISSUE THREAD

**Issue by SongZihui-sudo** [Lcry/a-sheep-assistant#114]
## 截图
![image](https://user-images.githubusercontent.com/77034643/191146607-45da5d03-f55f-4fb9-9f71-e0795b0b36c8.png)
## config.py
![image](https://user-images.githubusercontent.com/77034643/191146648-a5c319e3-138a-4795-8d39-a381bd6bc21a.png)

**Comment by hechengdu** [comment]
用手机app  stream 抓包 获取 token
用uid获取token  我也没成功过
