### ISSUE TITLE
再次报错 string indices must be integers

### ISSUE THREAD

**Issue by fucklinux** [Lcry/a-sheep-assistant#115]
![Screenshot_20220920_091706](https://user-images.githubusercontent.com/89513519/191146725-9efd0aaa-f8da-43c2-8def-cc206c429b4b.jpg)
新版本用 target_uid 模式又出现了 string indices must be integers 的错误。
另外想问一下，有没有只用手机就能快速抓 token 的方式？

**Comment by allonbrooks** [comment]
获取token接口错误

**Comment by superporn** [comment]
今天好像有更新了

**Comment by liang611zh** [comment]
第1次尝试换取用户uuid成功
开始尝试第1次换取用户header_t
{'err_code': 10001, 'err_msg': '参数错误', 'data': "Key: 'LoginOppoValidator.Token' Error:Field validation for 'Token' failed on the 'required' tag"}
string indices must be integers

**Comment by xiaochangbai** [comment]
期待大佬能破解啊

**Comment by Lcry** [comment]
官方接口失效
