### ISSUE TITLE
接口更新 关能过 皮肤能拿 但是入不了羊群

### ISSUE THREAD

**Issue by Composure17** [Lcry/a-sheep-assistant#117]
今天有大佬在群里说 可能加了时间限制
刚改了map_info_ex的可以设置成两关一样 但是 过了拿了皮肤 也没增加羊群

**Comment by Reckfu1** [comment]
> 今天有大佬在群里说 可能加了时间限制 刚改了map_info_ex的可以设置成两关一样 但是 过了拿了皮肤 也没增加羊群

map_info_ex还能改吗 我用的charles改了也没用了

**Comment by Lcry** [comment]
接口已失效
