### ISSUE TITLE
新刷榜方式

### ISSUE THREAD

**Issue by yanqinghao** [Lcry/a-sheep-assistant#121]
https://github.com/yanqinghao/sheep-assistant

**Comment by ocean-zhc** [comment]
有点复杂

**Comment by iWorkers** [comment]
最新刷榜接口https://cat-match.easygame2021.com/sheep/v1/game/update_user_skin?skin=24

**Comment by qq524422161** [comment]
自动化的工具抓包，可行。无聊不搞了
