### ISSUE TITLE
换取t接口报错：参数错误

### ISSUE THREAD

**Issue by jianweigit** [Lcry/a-sheep-assistant#123]
换取t的时候接口 `https://cat-match.easygame2021.com/sheep/v1/user/login_oppo` 报错 参数错误 
```
"Key: 'LoginOppoValidator.Token' Error:Field validation for 'Token' failed on the 'required' tag"
```
![截屏2022-09-21 16 20 31](https://user-images.githubusercontent.com/42216997/191453560-681fb3e6-f052-457f-b61a-b845aa658e38.png)

**Comment by wxy1343** [comment]
新接口`/sheep/v1/user/login_wx`
参数`code`
https://developers.weixin.qq.com/miniprogram/dev/api/open-api/login/wx.login.html

**Comment by qq524422161** [comment]
> 换取t的时候接口 `https://cat-match.easygame2021.com/sheep/v1/user/login_oppo` 报错 参数错误
> 
> ```
> "Key: 'LoginOppoValidator.Token' Error:Field validation for 'Token' failed on the 'required' tag"
> ```
> 
> ![截屏2022-09-21 16 20 31](https://user-images.githubusercontent.com/42216997/191453560-681fb3e6-f052-457f-b61a-b845aa658e38.png)

多抓包看
