### ISSUE TITLE
发现新的通关方法

### ISSUE THREAD

**Issue by jtc1246** [Lcry/a-sheep-assistant#125]
找到图中这个请求

<img width="1212" alt="截屏2022-09-24 00 25 02" src="https://user-images.githubusercontent.com/43341500/192008321-76a2035d-d1f4-4cc8-8453-a69ec570dd47.png">

把它改成左边这个样子（右边是原本的）

<img width="851" alt="截屏2022-09-24 00 23 09" src="https://user-images.githubusercontent.com/43341500/192008459-65dd06ee-9384-4c4e-a833-063a07d4ec49.png">

然后所有方块就变成相同的了，全部点掉就行

![WechatIMG685](https://user-images.githubusercontent.com/43341500/192008549-a2afb547-3c40-4953-8346-468c543a08a1.jpeg)

这个方法退出后再仍然是有效的

**Comment by poang** [comment]
> 找到图中这个请求
> 
> <img alt="截屏2022-09-24 00 25 02" width="1212" src="https://user-images.githubusercontent.com/43341500/192008321-76a2035d-d1f4-4cc8-8453-a69ec570dd47.png">
> 
> 把它改成左边这个样子（右边是原本的）
> 
> <img alt="截屏2022-09-24 00 23 09" width="851" src="https://user-images.githubusercontent.com/43341500/192008459-65dd06ee-9384-4c4e-a833-063a07d4ec49.png">
> 
> 然后所有方块就变成相同的了，全部点掉就行
> 
> ![WechatIMG685](https://user-images.githubusercontent.com/43341500/192008549-a2afb547-3c40-4953-8346-468c543a08a1.jpeg)
> 
> 这个方法退出后再仍然是有效的

请问这个值修改到哪里呢？

**Comment by huyikai** [comment]
好用😀 而且发现可以通过删除小程序后重新打开，多次进行游戏。所以每日是否进行游戏的状态，应该是存在了缓存中了。

**Comment by 504658278guo** [comment]
大神，能给个详细通关过程不？不会用抓包改包工具啊。

**Comment by whcxxb** [comment]
现在抓取不到了

**Comment by jtc1246** [comment]
是这样的，每天的map都是相同的。它只会去获取一次，然后就报存在本地了。只要微信主页下拉，把这个小程序删掉，再进入就可以了。

**Comment by huyikai** [comment]
> 现在抓取不到了

刚才又试了一下，还是可以的
![image](https://user-images.githubusercontent.com/25839948/192087900-c73274d8-f435-45c8-9cf4-76f4c35735fa.png)

**Comment by Mvpanswer7** [comment]
改了好像地图没有变，清了缓存，是第一次请求map

**Comment by whcxxb** [comment]
> > 现在抓不到了
> 
> 刚才又试了一下，还可以的 ![图片](https://user-images.githubusercontent.com/25839948/192087900-c73274d8-f435-45c8-9cf4-76f4c35735fa.png)

确实可以，现在加了时间限制了 哈哈只能一天一次

**Comment by Mvpanswer7** [comment]
实践了一下确实可以

**Comment by jtc1246** [comment]
这个方法好像已经不行了

**Comment by Mvpanswer7** [comment]
> 

xxxx.txt文件名改了，换一下就行了，但是为啥我用这个方法过了，历史排行榜里面还是没有+1

**Comment by jtc1246** [comment]
在前端过还是没问题的，但是它的验证方式升级了，所以服务器校验不通过。通过后会发送一个matchTypeInfo给服务器，以前这个matchTypeInfo是比较短的，刚刚matchTypeInfo是很长的一串。
