### ISSUE TITLE
这个值：eyxxxxxxxxx.xxxx 怎么没有？怎么获取啊

### ISSUE THREAD

**Issue by gubinjie** [Lcry/a-sheep-assistant#22]
![image](https://user-images.githubusercontent.com/37869445/190349020-1f8531c5-5654-4bc6-8590-7bd6fa8e2243.png)

**Comment by 122cygf** [comment]
看起来你的https没解密

**Comment by chunbai123** [comment]
把证书装上 进入游戏后玩一局 再数据包里找 不是每个包都包含t值

**Comment by gubinjie** [comment]
![image](https://user-images.githubusercontent.com/37869445/190372873-60f30614-6183-40ab-8049-9a082e03768c.png)
找了好几个这个地址的数据包都没有t值

**Comment by chentg2873** [comment]
> ![image](https://user-images.githubusercontent.com/37869445/190372873-60f30614-6183-40ab-8049-9a082e03768c.png) 找了好几个这个地址的数据包都没有t值

t在https的请求里面

**Comment by chentg2873** [comment]
https没有解密

**Comment by gubinjie** [comment]
@chentg2873 这个地址也是https://cat-match....开头的吗

**Comment by mryudongdong** [comment]
同问怎么获取t值

**Comment by chentg2873** [comment]
> @chentg2873 这个地址也是[https://cat-match....开头的吗](https://cat-match....%E5%BC%80%E5%A4%B4%E7%9A%84%E5%90%97)

是这个开头，要安装https证书
![image](https://user-images.githubusercontent.com/79957313/190399496-6d2e29ec-f27a-4d78-a379-262e320a3392.png)

**Comment by mryudongdong** [comment]
> 

请问证书怎么安装

**Comment by chentg2873** [comment]
> > 
> 
> 请问证书怎么安装

你百度一下你用的那个抓包软件怎么安装https证书，一堆教程

**Comment by mryudongdong** [comment]
> > > 
> > 
> > 
> > 请问证书怎么安装
> 
> 你百度一下你用的那个抓包软件怎么安装https证书，一堆教程

我弄好了，就是安装python依赖又出问题了

**Comment by zhaowei1994** [comment]
我是台式机。。。这咋办安装不了证书，苹果手机

**Comment by jinijihui** [comment]
> > > 
> > 
> > 
> > 请问证书怎么安装
> 
> 你百度一下你用的那个抓包软件怎么安装https证书，一堆教程

安装了证书，还是无法解密。。。 真TM奇怪
