### ISSUE TITLE
传入t后提示没有权限

### ISSUE THREAD

**Issue by qilong1997** [Lcry/a-sheep-assistant#25]

**Comment by qilong1997** [comment]
![image](https://user-images.githubusercontent.com/48241189/190366190-5cb414d3-6dc7-433e-9afc-52a2ff354dd5.png)

**Comment by Lcry** [comment]
获取的t值不对或者已经刷新失效了

**Comment by qilong1997** [comment]
域名是umini.shujupei.com, 下图响应主体里面的ey开头的这一串
![image](https://user-images.githubusercontent.com/48241189/190367790-d20326ef-ccd4-46b5-b689-18e1b9d11531.png)

**Comment by chunbai123** [comment]
不是这个地址的 你这个t值不对 t在协议头里 域名是cat-match的

**Comment by yuzhenlin046** [comment]
为什么我用Fiddler Everywhere访问PC端微信小程序抓不到，页面都没问题

**Comment by qilong1997** [comment]
👍🏻

**Comment by chunbai123** [comment]
> 

代理没挂好 建议直接用手机上的抓包软件直接抓
