### ISSUE TITLE
请教一下，ios 加 charles 为啥抓不到 finish_api呢

### ISSUE THREAD

**Issue by Yann-River** [Lcry/a-sheep-assistant#27]
请教一下，ios 加 charles 为啥抓不到 finish_api呢。感谢

**Comment by Lcry** [comment]
ios建议用stream抓吧

**Comment by Roleran** [comment]
您好，我用stream抓取的t是：eyxxxxxx.eyxxxxxxxxxxxxxjoiIn0.tEhDxxxxxxx
这样的，运行之后python报错SyntaxError: EOL while scanning string literal，这样是什么问题呀您知道吗？我就修改了t和user-agent。

**Comment by Lcry** [comment]
> 您好，我用stream抓取的t是：eyxxxxxx.eyxxxxxxxxxxxxxjoiIn0.tEhDxxxxxxx 这样的，运行之后python报错SyntaxError: EOL while scanning string literal，这样是什么问题呀您知道吗？我就修改了t和user-agent。

改配置的导致代码出问题了吧，仔细检查一下是否替换对了

**Comment by Roleran** [comment]
> > 您好，我用stream抓取的t是：eyxxxxxx.eyxxxxxxxxxxxxxjoiIn0.tEhDxxxxxxx 这样的，运行之后python报错SyntaxError: EOL while scanning string literal，这样是什么问题呀您知道吗？我就修改了t和user-agent。
> 
> 改配置的导致代码出问题了吧，仔细检查一下是否替换对了

嗯现在好了，感谢！

**Comment by 18551891189** [comment]
所以苹果➕p c到底咋连起来啊大佬们

**Comment by yuzhenlin046** [comment]
![12](https://user-images.githubusercontent.com/21291586/190538927-8035dc12-e025-43b5-b94a-32401da0dc4c.jpg)
我这stream为啥抓不到，开始抓包后游戏网络就不行了好像是受到vpn影响

**Comment by yuzhenlin046** [comment]
![12](https://user-images.githubusercontent.com/21291586/190539087-afd0d88f-5c20-4d7d-9ca5-763b9d09a0ac.jpg)

**Comment by Yann-River** [comment]
感谢
