### ISSUE TITLE
header里面的t在哪啊

### ISSUE THREAD

**Issue by daydreamqun** [Lcry/a-sheep-assistant#29]

**Comment by fengchenguang** [comment]
同问

**Comment by mrmoll** [comment]
域名是cat-match的里面有

**Comment by daydreamqun** [comment]
> 

我这个域名下的都没有诶。。
![origin_img_v2_c8ecb456-7c05-4ded-9edf-0314d6f565cg](https://user-images.githubusercontent.com/63582755/190400022-4c005785-f2f1-4524-b79d-ebcea14292d4.jpg)

**Comment by mrmoll** [comment]
> > 
> 
> 我这个域名下的都没有诶。。 ![origin_img_v2_c8ecb456-7c05-4ded-9edf-0314d6f565cg](https://user-images.githubusercontent.com/63582755/190400022-4c005785-f2f1-4524-b79d-ebcea14292d4.jpg)

这个用的是stream抓的吗 证书装了没

**Comment by fengchenguang** [comment]
懂啦，认证下载之后没有添加信任。（实际上另外一个帖子也讨论了，就是没解密）

**Comment by daydreamqun** [comment]
> 

咦我信任了呀 能看看你的信任那一页截图吗

**Comment by daydreamqun** [comment]
> > > 
> > 
> > 
> > 我这个域名下的都没有诶。。 ![origin_img_v2_c8ecb456-7c05-4ded-9edf-0314d6f565cg](https://user-images.githubusercontent.com/63582755/190400022-4c005785-f2f1-4524-b79d-ebcea14292d4.jpg)
> 
> 这个用的是stream抓的吗 证书装了没

是呀也信任了

**Comment by mrmoll** [comment]
不是这个链接   找找其他cat-match  你这个cat-match 前面带了connect   我的带connect里面也没有东西

**Comment by daydreamqun** [comment]
> 不是这个链接 找找其他cat-match 你这个cat-match 前面带了connect 我的带connect里面也没有东西

t就是 t: 后面的东西么

**Comment by mrmoll** [comment]
> > 不是这个链接 找找其他cat-match 你这个cat-match 前面带了connect 我的带connect里面也没有东西
> 
> t就是 t: 后面的东西么

是的

**Comment by daydreamqun** [comment]
> > > 不是这个链接 找找其他cat-match 你这个cat-match 前面带了connect 我的带connect里面也没有东西
> > 
> > 
> > t就是 t: 后面的东西么
> 
> 是的

哇我为什么没有啊 裂开了

**Comment by mrmoll** [comment]
> > > > 不是这个链接 找找其他cat-match 你这个cat-match 前面带了connect 我的带connect里面也没有东西
> > > 
> > > 
> > > t就是 t: 后面的东西么
> > 
> > 
> > 是的
> 
> 哇我为什么没有啊 裂开了

好像是游戏刚刚版本更新了  ，  我现在也没有了

**Comment by mrmoll** [comment]
> > > > 不是这个链接 找找其他cat-match 你这个cat-match 前面带了connect 我的带connect里面也没有东西
> > > 
> > > 
> > > t就是 t: 后面的东西么
> > 
> > 
> > 是的
> 
> 哇我为什么没有啊 裂开了

你玩游戏   简单的那关点完，到第二关的时候随便点几下 再停止抓包

**Comment by mrmoll** [comment]
> cat-match

cat-match.easygame的域名  不带static

**Comment by daydreamqun** [comment]
> cat-match.easygame的域名 不带static

我直接进不去游戏了哈哈哈 就一直在加载 进不去游戏

**Comment by daydreamqun** [comment]
> > cat-match
> 
> cat-match.easygame的域名 不带static

哇气死我了这个域名下也没有 没有t

**Comment by daydreamqun** [comment]
> > cat-match
> 
> cat-match.easygame的域名 不带static

能截个图让我看一眼你的啥样嘛

**Comment by mrmoll** [comment]
> > > cat-match
> > 
> > 
> > cat-match.easygame的域名 不带static
> 
> 哇气死我了这个域名下也没有 没有t

进stream  设置那边第一个图标是https抓包  ，点进去  如果你证书是信任的，会有一行提示叫  设置成功:ca证书已经安装且信任， 然后返回 抓包， 然后进微信玩游戏  玩到第二个  然后停止抓包    到抓包历史里 找打刚抓的 按域名排序  找到cat-match.easygam2021   不带static的那个域名  进去之后从最近一个请求连接找

**Comment by mrmoll** [comment]
> > > cat-match
> > 
> > 
> > cat-match.easygame的域名 不带static
> 
> 能截个图让我看一眼你的啥样嘛

你去另外一个提问下找， 有别人抓到t值的截图，t值被他打码了，   “这个值：eyxxxxxxxxx.xxxx 怎么没有“   这个问题下面 chentg2873这个人发的截图

**Comment by daydreamqun** [comment]
> 

好了！！！还是证书没有走到第二步信任哈哈哈哈 谢谢！！！
