### ISSUE TITLE
赶紧删了！

### ISSUE THREAD

**Issue by k-kyle** [Lcry/a-sheep-assistant#30]
太好用了，一次成功，我clone了，赶紧删了把！！

**Comment by LongInes0127** [comment]
请问为什么我不可以啊

**Comment by caiqingxunzzZ** [comment]
想问问怎么找t值

**Comment by Lcry** [comment]
> 太好用了，一次成功，我clone了，赶紧删了把！！

我劝你善良

**Comment by CCTGZZ** [comment]
> > 太好用了，一次成功，我clone了，赶紧删了把！！
> 
> 咋找t啊 header里面没有啊

有的好好找找

**Comment by Zhuozy** [comment]
过了河就得把桥拆掉 >_<

**Comment by Ljfmmy** [comment]
好家伙，自己玩完就劝人删库！！！
