### ISSUE TITLE
是ios抓包然后pc可以运行么

### ISSUE THREAD

**Issue by Morningstar219** [Lcry/a-sheep-assistant#34]
作者好像更新了。。。

**Comment by 13013062061** [comment]
我也想知道怎么运行

**Comment by Lcry** [comment]
是服务器已经无法及时响应了。。。。。游戏都打不开，请游戏能打开的时候再试试

**Comment by mrmoll** [comment]
> 是服务器已经无法及时响应了。。。。。游戏都打不开，请游戏能打开的时候再试试

有个刷了40万次的  我估计就是他把服务器刷挂了，。。。。
