### ISSUE TITLE
怎么找t

### ISSUE THREAD

**Issue by 250aaad** [Lcry/a-sheep-assistant#36]
![image](https://user-images.githubusercontent.com/108048370/190419257-4722a9d6-2ffe-482c-969a-e7fe32f80099.png)

**Comment by 250aaad** [comment]
是要进入main.py里的网址吗

**Comment by CCTGZZ** [comment]
> 

你得先抓到包再说呀

**Comment by 250aaad** [comment]
> > 
> 
> 你得先抓到包再说呀

游戏崩了，怪不得没抓到

**Comment by Dream-Ling** [comment]
> ![image](https://user-images.githubusercontent.com/108048370/190419257-4722a9d6-2ffe-482c-969a-e7fe32f80099.png)

这是什么抓包工具啊

**Comment by taoman** [comment]
> > ![image](https://user-images.githubusercontent.com/108048370/190419257-4722a9d6-2ffe-482c-969a-e7fe32f80099.png)
> 
> 这是什么抓包工具啊

fiddler
