### ISSUE TITLE
安卓无法成功

### ISSUE THREAD

**Issue by youzeFix** [Lcry/a-sheep-assistant#37]
PC fiddler连接手机代理进不了游戏，点挑战按钮没反应，抓包有一个网址报错502；

安卓HttpCanray代理后无法打开游戏，进度条卡住不动。

有没有人安卓成功的？

**Comment by youzeFix** [comment]
> 游戏都崩了，还在抓包- -。

应该没有，不连代理正常的

**Comment by youzeFix** [comment]
> > PC fiddler连接手机代理进不了游戏，点挑战按钮没反应，抓包有一个网址报错502；
> > 安卓HttpCanray代理后无法打开游戏，进度条卡住不动。
> > 有没有人安卓成功的？
> 
> 证书问题，安卓7.0和微信7.0以后不会信任用户证书了，你用虚拟机吧如果有root权限可以本机，吧证书导入系统证书就可以抓了

多谢！

**Comment by zhaowei1994** [comment]
我直接电脑打开小程序接口是啥，可以这样整吗
