### ISSUE TITLE
fiddler 没有返回 t 值 ?

### ISSUE THREAD

**Issue by xiaobinqt** [Lcry/a-sheep-assistant#39]
![image](https://user-images.githubusercontent.com/23259661/190451320-56c94f8e-cab7-45ab-bf0a-44fcaeb44e3d.png)

没有看到 t 值，求教。

**Comment by hwhaocool** [comment]
你看的请求不对，你看的是 `tunnel` 是建立连接的，要看另外一个
![image](https://user-images.githubusercontent.com/20699977/190453875-b702f6d6-6dec-4837-8a54-6a2056f3a97e.png)

**Comment by Aurora15304** [comment]
fd不能抓wx小程序的吧

**Comment by P1an8** [comment]
怎么抓的，我PC抓不到

**Comment by Aurora15304** [comment]
> 

用模拟器抓 或者用手机抓就行了 安卓模拟器里面用httpcanary 抓到t值用pc挂着线程就行

**Comment by lyk1205** [comment]
> > 
> 
> 用模拟器抓 或者用手机抓就行了 安卓模拟器里面用httpcanary 抓到t值用pc挂着线程就行
httpcanary 哪里可以下载

**Comment by lyk1205** [comment]
> 你看的请求不对，你看的是 `tunnel` 是建立连接的，要看另外一个 ![image](https://user-images.githubusercontent.com/20699977/190453875-b702f6d6-6dec-4837-8a54-6a2056f3a97e.png)

![image](https://user-images.githubusercontent.com/84303774/190569009-fdd4d920-5ca5-416e-a309-273cb52e40c4.png)
这好像没t值了
