### ISSUE TITLE
刷了一百多万数据被清零了

### ISSUE THREAD

**Issue by bby0** [Lcry/a-sheep-assistant#44]
![Uploading 6DCB1DD2-0E79-41E3-8A1E-FF02CA58B0D6.png…]()

**Comment by Lcry** [comment]
游戏设定而已，请勿恶意请求

**Comment by zsh2401** [comment]
那之后还可以刷吗？还是就一直归零了？求解！

**Comment by bby0** [comment]
可以，又刷了9999999999999

Seymour Zhang ***@***.***> 于2022年9月19日周一 01:31写道：
