### ISSUE TITLE
感谢大佬

### ISSUE THREAD

**Issue by 841828078** [Lcry/a-sheep-assistant#45]

**Comment by 841828078** [comment]
<img width="335" alt="屏幕截图 2022-09-16 090114" src="https://user-images.githubusercontent.com/47712496/190534314-688e76b5-513a-44ea-b5fd-eaef99445ba1.png">

**Comment by imarman** [comment]
> <img alt="屏幕截图 2022-09-16 090114" width="335" src="https://user-images.githubusercontent.com/47712496/190534314-688e76b5-513a-44ea-b5fd-eaef99445ba1.png">
大佬是怎么抓到的

**Comment by 841828078** [comment]
> 

照着大佬说的，用stream抓到t，运行脚本就行了

**Comment by ihatekkken** [comment]
我IP好像被封了，我把t给你，你帮我运行一下？

**Comment by a102068** [comment]
> 

可以发给我，我帮你跑

**Comment by ihatekkken** [comment]
> > 
> 
> 可以发给我，我帮你跑

我可以跑了，就是小程序崩了，谢谢你噢
