### ISSUE TITLE
太牛了，好像只能改一次哈哈哈哈！！！

### ISSUE THREAD

**Issue by BoomRich88888888** [Lcry/a-sheep-assistant#48]
感谢大佬！！！！

**Comment by lyk1205** [comment]
你怎么抓包的，现在好像抓不了

**Comment by BoomRich88888888** [comment]
> 你怎么抓包的，现在好像抓不了

小程序：羊了个羊 现在首页展示空白，应该是出bug了他们

**Comment by yumaopiaoa** [comment]
抓到t了

**Comment by lyk1205** [comment]
> 

用什么抓的

**Comment by BoomRich88888888** [comment]
> > 
> 
> 用什么抓的

Charles随便一个抓包工具都可

**Comment by lyk1205** [comment]
> > > 
> > 
> > 
> > 用什么抓的
> 
> Charles随便一个抓包工具都可
微信现在抓不了吧

**Comment by BoomRich88888888** [comment]
> 

服务器崩了吧，第一关都进不去

**Comment by bbhxwl** [comment]
> > > 
> > 
> > 
> > 用什么抓的
> 
> Charles随便一个抓包工具都可

我用mitmweb 抓的，没看到呢。
