### ISSUE TITLE
这是啥问题

### ISSUE THREAD

**Issue by vaw-z** [Lcry/a-sheep-assistant#52]
![image](https://user-images.githubusercontent.com/110016655/190548315-6ef900dd-77d1-4c4f-a7b7-44996c3fb7fe.png)

**Comment by wank1r** [comment]
羊了个羊又崩了，不是你的问题

**Comment by vaw-z** [comment]
> 

扫噶

**Comment by vaw-z** [comment]
> 羊了个羊又崩了，不是你的问题

扫噶
