### ISSUE TITLE
Mac 是不是抓不到t 啊

### ISSUE THREAD

**Issue by AlienChao** [Lcry/a-sheep-assistant#54]
Mac中没法打开小程序， 抓包手机的。又都是乱码

**Comment by yuerdev** [comment]
+1 ，抓头中。。。。。。。

**Comment by Sta-sky** [comment]
最新版微信3.7.6是不是抓不了包啊  我之前没升级可以抓到  升级后抓不到了哇

**Comment by yuerdev** [comment]
用安卓抓，别用mac抓，mac抓游戏会失败不好玩，我用安卓抓了
