### ISSUE TITLE
由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。

### ISSUE THREAD

**Issue by Zhuozy** [Lcry/a-sheep-assistant#58]
![image](https://user-images.githubusercontent.com/59716354/190562417-70cf5eb1-6f05-4f3f-89d1-e0382c8e985e.png)
友友们这是咋回事？

**Comment by Zhuozy** [comment]
iPhone上获取的t和user-agent不能在Windows上用吗？

**Comment by vaw-z** [comment]
> ![image](https://user-images.githubusercontent.com/59716354/190562417-70cf5eb1-6f05-4f3f-89d1-e0382c8e985e.png) 友友们这是咋回事？

不是你的问题，游戏崩了进不去，我之前也是

**Comment by Liukkkc** [comment]
> > ![image](https://user-images.githubusercontent.com/59716354/190562417-70cf5eb1-6f05-4f3f-89d1-e0382c8e985e.png) 友友们这是咋回事？
> 
> 不是你的问题，游戏崩了进不去，我之

> > ![image](https://user-images.githubusercontent.com/59716354/190562417-70cf5eb1-6f05-4f3f-89d1-e0382c8e985e.png) 友友们这是咋回事？
> 
> 不是你的问题，游戏崩了进不去，我之前也是

现在行了吗？

**Comment by Zhuozy** [comment]
> > > ![image](https://user-images.githubusercontent.com/59716354/190562417-70cf5eb1-6f05-4f3f-89d1-e0382c8e985e.png) 友友们这是咋回事？
> > 
> > 
> > 不是你的问题，游戏崩了进不去，我之
> 
> > > ![image](https://user-images.githubusercontent.com/59716354/190562417-70cf5eb1-6f05-4f3f-89d1-e0382c8e985e.png) 友友们这是咋回事？
> > 
> > 
> > 不是你的问题，游戏崩了进不去，我之前也是
> 
> 现在行了吗？
有时候行，有时候不行，服务器压力太大了

**Comment by Zhuozy** [comment]
兄弟们轻点跑，连不上了啊 ~~~

**Comment by tomorrow-yes** [comment]
![Uploading 7007c2b75ca003b2be6caa696addaed.png…]()
搞不定啊

**Comment by Lcry** [comment]
1、更新最新代码
2、不要开任何代理以及抓包工具
3、若2满足还是一次不成功，请过段时间再试
