### ISSUE TITLE
远程主机强迫关闭了一个现有的连接

### ISSUE THREAD

**Issue by clownice** [Lcry/a-sheep-assistant#63]
游戏服务器响应超时或崩溃中未及时响应，缓缓吧，等待服务器恢复后再试！本次程序运行结束，错误日志: HTTPSConnectionPool(host='cat-match.easygame2021.com', port=443): Max retries exceeded with url: /sheep/v1/game/game_over?rank_score=1&rank_state=1&rank_time=1945&rank_role=1&skin=1 (Caused by ProxyError('Cannot connect to proxy.', ConnectionResetError(10054, '远 程主机强迫关闭了一个现有的连接。', None, 10054, None)))

这是程序不能用了吗

**Comment by Lianting-Wang** [comment]
same problem...

**Comment by YZY74224** [comment]
这是被你们这群老六搞的服务器响应不过来了，等等就行

**Comment by Lcry** [comment]
服务器无法承受压力
