### ISSUE TITLE
 有刷皮肤的请求地址吗

### ISSUE THREAD

**Issue by ShayLau** [Lcry/a-sheep-assistant#66]

**Comment by XiaoXiao-Lu** [comment]
同求

**Comment by ShayLau** [comment]
在代理里面,通过在 rewrite_remote  重写规则里面添加获取第二关地图的规则,完成通关,通关后送皮肤
参考https://github.com/missuo/FuckSheepGame

**Comment by Lcry** [comment]
皮肤在本地，不能实现多端同步
