### ISSUE TITLE
有人能解释下t是啥意思吗，没找到啊

### ISSUE THREAD

**Issue by Dream-Ling** [Lcry/a-sheep-assistant#69]
有人能解释下t是啥意思吗，没找到啊

**Comment by wowaugenstern** [comment]
登陆接口，小程序要登陆授权一下就看到了，{"err_code":0,"err_msg":"","data":{"openid":"","token":"","uid":}}，t是里面的token值

**Comment by iyuyoung** [comment]
t就是Token，登录以后会返回，同时返回的还有openID，uid

**Comment by Lcry** [comment]
无关issues
