### ISSUE TITLE
游戏服务器响应超时或崩溃中未及时响应，缓缓吧，等待服务器恢复后再试！本次程序运行结束

### ISSUE THREAD

**Issue by Punny520** [Lcry/a-sheep-assistant#77]
Max retries exceeded
是被禁了么？游戏服务器感觉没问题啊？

**Comment by Punny520** [comment]
，错误日志: HTTPSConnectionPool(host='cat-match.easygame2021.com', port=443): Max retries exceeded with url: /sheep/v1/game/game_over?rank_score=1&rank_state=1&rank_time=800&rank_role=1&skin=1 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001EF6FD999C0>, 'Connection to cat-match.easygame2021.com timed out. (connect timeout=6)'))

**Comment by zhaozekai456** [comment]
我也是 怎么回事

**Comment by tomorrow-yes** [comment]
还是有用的，我直接循环600次成功25次了

**Comment by tan90du-sx** [comment]
同样的问题

**Comment by tan90du-sx** [comment]
> 

你是怎么成功的啊

**Comment by lyk1205** [comment]
可以看我仓库，改了下代码，异步更快

**Comment by lyk1205** [comment]
> 可以看我的仓库，改了下代码，类似的定位

走量哈哈哈

**Comment by Lcry** [comment]
官方限流限制
