### ISSUE TITLE
token的有效时长

### ISSUE THREAD

**Issue by xmexg** [Lcry/a-sheep-assistant#78]
获取一次token能一直用起来吗?还是有时间限制?

**Comment by iyuyoung** [comment]
`{"exp":1694418432,"nbf":1663316232,"iat":1663314432,"jti":"CM:","open_id":"","uid":,"debug":"","lang":""}`
不用担心，刚才解析了一下，有效期到2023年9月

**Comment by xmexg** [comment]
不同的微信小程序token是一样的吗?他和微信开发文档的access_token有什么关系?https://developers.weixin.qq.com/doc/offiaccount/Basic_Information/Get_access_token.html

**Comment by iyuyoung** [comment]
肯定是不一样的呀，token就相当于是秘钥，每个产品都是自己的Token生成规则，但是大部分都使用JWT，羊了个羊也是JWT

**Comment by xmexg** [comment]
多谢
