### ISSUE TITLE
请问一下大佬们 requests模块安装失败怎么搞

### ISSUE THREAD

**Issue by Zta0n** [Lcry/a-sheep-assistant#79]
D:\sheep\a-sheep-assistant-main>pip3 install -r requirements.txt -i https://pypi.tuna.tsinghua.edu.cn/simple
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Requirement already satisfied: requests in c:\program files\python\lib\site-packages (from -r requirements.txt (line 1)) (2.24.0)
Requirement already satisfied: idna<3,>=2.5 in c:\program files\python\lib\site-packages (from requests->-r requirements.txt (line 1)) (2.10)
Requirement already satisfied: certifi>=2017.4.17 in c:\program files\python\lib\site-packages (from requests->-r requirements.txt (line 1)) (2020.6.20)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in c:\program files\python\lib\site-packages (from requests->-r requirements.txt (line 1)) (1.25.10)
Requirement already satisfied: chardet<4,>=3.0.2 in c:\program files\python\lib\site-packages (from requests->-r requirements.txt (line 1)) (3.0.4)

**Comment by k-kyle** [comment]
用虚拟环境吧，你这环境有冲突

**Comment by kingthai** [comment]
更换下数据源
pip3 install -r requirements.txt  -i http://pypi.douban.com/simple --trusted-host=pypi.douban.com

**Comment by Lcry** [comment]
可能跟版本有关系，多尝试
