### ISSUE TITLE
啥时候再更新，这个版本不行了

### ISSUE THREAD

**Issue by yangCHEN121520** [Lcry/a-sheep-assistant#89]

**Comment by yangCHEN121520** [comment]
我的问题 代理忘记关了QAQ

**Comment by Lcry** [comment]
更新最新版本了吗，2022年9月17日 10:09:39执行成功啊
【羊了个羊一键闯关启动】
...第1次尝试完成闯关...
生成随机时间间隔，防止游戏服务器接口限流导致失败 : 2 s
生成随机闯关完成耗时: 105 s
恭喜你! 本次闯关羊群状态成功
恭喜你! 本次闯关话题状态成功
已成功完成2次
...第2次尝试完成闯关...
生成随机时间间隔，防止游戏服务器接口限流导致失败 : 6 s
恭喜你! 本次闯关羊群状态成功
恭喜你! 本次闯关话题状态成功
已成功完成4次
...第3次尝试完成闯关...
生成随机时间间隔，防止游戏服务器接口限流导致失败 : 6 s
恭喜你! 本次闯关羊群状态成功

**Comment by yangCHEN121520** [comment]
> 更新最新版本了吗，2022年9月17日 10:09:39执行成功啊 【羊了个羊一键闯关启动】 ...第1次尝试完成闯关... 生成随机时间间隔，防止游戏服务器接口限流导致失败 : 2 s 生成随机闯关完成耗时: 105 s 恭喜你! 本次闯关羊群状态成功 恭喜你! 本次闯关话题状态成功 已成功完成2次 ...第2次尝试完成闯关... 生成随机时间间隔，防止游戏服务器接口限流导致失败 : 6 s 恭喜你! 本次闯关羊群状态成功 恭喜你! 本次闯关话题状态成功 已成功完成4次 ...第3次尝试完成闯关... 生成随机时间间隔，防止游戏服务器接口限流导致失败 : 6 s 恭喜你! 本次闯关羊群状态成功

是的  我刚才忘记关代理了 他就一直失败QAQ
