### ISSUE TITLE
好像不行了

### ISSUE THREAD

**Issue by Championkid** [Lcry/a-sheep-assistant#90]
游戏服务器响应超时或崩溃中未及时响应，缓缓吧，等待服务器恢复后再试！本次失败请忽略，错误日志: HTTPSConnectionPool(host='cat-match.easygame2021.com', port=443): Max retries exceeded with url: /sheep/v1/game/game_over?rank_score=1&rank_state=1&rank_time=1&rank_role=1&skin=1 (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1107: The handshake operation timed out')))

一直是这个

**Comment by lpz1096** [comment]
是的，我也是一直是这个

**Comment by Lcry** [comment]
都提示这么明白了有啥不行的

**Comment by Championkid** [comment]
哈哈哈哈哈哈哈哈哈哈哈哈哈哈
