### ISSUE TITLE
vps安装依赖提示错误

### ISSUE THREAD

**Issue by wulongjiasu** [Lcry/a-sheep-assistant#94]
ERROR: Could not open requirements file: [Errno 2] No such filehttps://docs.github.com/github/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-for
![Snipaste_2022-09-17_13-39-23](https://user-images.githubusercontent.com/58661828/190842328-39e11d63-0cf1-46a6-92b0-281babc79047.png)
matting-syntax or directory: 'requirements.txt'

**Comment by NewDeveloper-DoubleW** [comment]
Could not find the file(requirements.txt)

**Comment by lixwen** [comment]
switch to main branch

**Comment by Lcry** [comment]
无效issues

**Comment by niyongsheng** [comment]
`pip freeze > requirements.txt`
