### ISSUE TITLE
游戏服务器响应超时或崩溃中未及时响应，缓缓吧，等待服务器恢复后再试！

### ISSUE THREAD

**Issue by Zeke-chin** [Lcry/a-sheep-assistant#98]
一直报这个东西 跑不出来呀
![image](https://user-images.githubusercontent.com/84116651/190853629-a0cbd4ec-63fd-4f78-894c-99914a13aeed.png)

**Comment by Lcry** [comment]
1、更新最新代码
2、不要开任何代理以及抓包工具后跑代码
3、若2满足还是一次不成功，请过段时间再试

**Comment by Zeke-chin** [comment]
> 1、更新最新代码 2、不要打开任何代理以及抓包工具后跑代码 3、若2满足还是一次不成功，请过段时间再试

问题已经解决 应该是因为我家里zerotier有net转发 所以家里全局都有代理
换了个阿里云的服务器成功跑通！
