### ISSUE TITLE
请问如何刷皮肤

### ISSUE THREAD

**Issue by zhang-wen-guang** [Lcry/a-sheep-assistant#99]
我看到代码中finish_game_sheep函数的第一个参数是skin，我尝试将这个值改为非1的值，通关后发现皮肤并没有变多。想问下是我修改的方式有问题吗？

**Comment by DarkArmed** [comment]
这个skin参数不是获取新的皮肤。目测有个专门获取新皮肤的接口，现在还没支持。

**Comment by Lcry** [comment]
皮肤应该不会支持了，皮肤都是本地操作，需要进行篡改替换操作才行

**Comment by 122cygf** [comment]
皮肤好像是保存在本地的呢，我换个设备就没了

**Comment by zhang-wen-guang** [comment]
哦，了解了，多谢各位。
